// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJOU8KodQzL-R8SDvMS_6EHUxA-Q3bUA',
    appId: '1:648238964269:web:2de6d15eeba1a6506e62a4',
    messagingSenderId: '648238964269',
    projectId: 'painp-ecbfc',
    authDomain: 'painp-ecbfc.firebaseapp.com',
    storageBucket: 'painp-ecbfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZEuavzzkLUe1XBvwZtyGXl2lpRx_E20',
    appId: '1:648238964269:android:060de7d1d3a1f7f56e62a4',
    messagingSenderId: '648238964269',
    projectId: 'painp-ecbfc',
    storageBucket: 'painp-ecbfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo5qy23-_QI9pfBtO2Vfi742YQyP5QQVo',
    appId: '1:648238964269:ios:50381e4b62496b4e6e62a4',
    messagingSenderId: '648238964269',
    projectId: 'painp-ecbfc',
    storageBucket: 'painp-ecbfc.firebasestorage.app',
    iosBundleId: 'com.example.painpoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo5qy23-_QI9pfBtO2Vfi742YQyP5QQVo',
    appId: '1:648238964269:ios:50381e4b62496b4e6e62a4',
    messagingSenderId: '648238964269',
    projectId: 'painp-ecbfc',
    storageBucket: 'painp-ecbfc.firebasestorage.app',
    iosBundleId: 'com.example.painpoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFJOU8KodQzL-R8SDvMS_6EHUxA-Q3bUA',
    appId: '1:648238964269:web:d707ec8b38a2a8646e62a4',
    messagingSenderId: '648238964269',
    projectId: 'painp-ecbfc',
    authDomain: 'painp-ecbfc.firebaseapp.com',
    storageBucket: 'painp-ecbfc.firebasestorage.app',
  );
}
